11-03-2021 13:00:30 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:01:01 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:01:21 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:01:27 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:06:14 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 13:06:38 WARNING  [log.py:224] Not Found: /
11-03-2021 13:06:38 WARNING  [log.py:224] Not Found: /favicon.ico
11-03-2021 13:06:45 WARNING  [log.py:224] Not Found: /api/user/token/
11-03-2021 13:07:00 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 13:07:00 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 13:07:00 WARNING  [log.py:224] Method Not Allowed: /api/user/register/
11-03-2021 13:08:15 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 13:08:15 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 13:09:40 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 13:09:40 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 13:09:40 WARNING  [log.py:224] Bad Request: /api/user/register/
11-03-2021 13:23:30 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/models.py changed, reloading.
11-03-2021 13:23:30 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:23:33 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 13:28:58 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:28:58 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:57:09 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 13:57:17 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 13:57:17 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 13:57:17 WARNING  [log.py:224] Method Not Allowed: /api/user/register/
11-03-2021 13:57:21 WARNING  [log.py:224] Not Found: /api/user
11-03-2021 13:57:24 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 13:57:24 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 13:57:24 WARNING  [log.py:224] Method Not Allowed: /api/user/token/
11-03-2021 13:57:34 WARNING  [log.py:224] Unauthorized: /api/user/token/
11-03-2021 13:57:45 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 13:57:45 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 13:57:45 WARNING  [log.py:224] Method Not Allowed: /api/user/register/
11-03-2021 13:57:59 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 13:57:59 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 13:57:59 WARNING  [log.py:224] Bad Request: /api/user/register/
11-03-2021 13:58:05 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 13:58:05 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 13:58:05 WARNING  [log.py:224] Too Many Requests: /api/user/register/
11-03-2021 13:58:13 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:58:13 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:58:15 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 13:58:28 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 13:58:28 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 13:58:37 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 13:58:37 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 13:58:37 WARNING  [log.py:224] Method Not Allowed: /api/user/token/
11-03-2021 13:58:47 WARNING  [log.py:224] Unauthorized: /api/user/token/
11-03-2021 13:59:09 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:59:10 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:59:16 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 13:59:38 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:00:31 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/admin.py changed, reloading.
11-03-2021 14:00:31 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:00:32 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:01:05 ERROR    [log.py:224] Internal Server Error: /api/user/token/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'function' object has no attribute 'mobile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 25, in post
    return Response(data={"data": serializer.data},
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 248, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `mobile` on serializer `CreateTokenSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `method` instance.
Original exception text was: 'function' object has no attribute 'mobile'.
11-03-2021 14:02:18 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:02:18 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:02:18 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:02:20 ERROR    [log.py:224] Internal Server Error: /api/user/token/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'function' object has no attribute 'mobile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 25, in post
    return Response(data={"data": serializer.data},
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 248, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `mobile` on serializer `CreateTokenSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `method` instance.
Original exception text was: 'function' object has no attribute 'mobile'.
11-03-2021 14:02:51 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:02:51 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:02:52 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:02:56 ERROR    [log.py:224] Internal Server Error: /api/user/token/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 24, in post
    serializer.is_valid(raise_exception=True)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 46, in validate
    return attrs.tokens
AttributeError: 'collections.OrderedDict' object has no attribute 'tokens'
11-03-2021 14:03:55 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:03:55 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:03:55 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:04:00 ERROR    [log.py:224] Internal Server Error: /api/user/token/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 95, in get_attribute
    instance = instance[attr]
KeyError: 'mobile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 25, in post
    return Response(data={"data": serializer.data},
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 248, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
KeyError: "Got KeyError when attempting to get a value for field `mobile` on serializer `CreateTokenSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'mobile'."
11-03-2021 14:05:12 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:05:12 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:05:12 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:05:15 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:05:15 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:05:29 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:05:29 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:05:29 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:06:03 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:06:03 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:06:03 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:06:20 ERROR    [log.py:224] Internal Server Error: /api/user/token/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 95, in get_attribute
    instance = instance[attr]
KeyError: 'mobile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 25, in post
    return Response(data={"data": serializer.data},
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 248, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
KeyError: "Got KeyError when attempting to get a value for field `mobile` on serializer `CreateTokenSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'mobile'."
11-03-2021 14:06:35 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:06:35 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:06:35 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:06:38 ERROR    [log.py:224] Internal Server Error: /api/user/token/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 95, in get_attribute
    instance = instance[attr]
KeyError: 'mobile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 25, in post
    return Response(data={"data": serializer.data},
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 248, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
KeyError: "Got KeyError when attempting to get a value for field `mobile` on serializer `CreateTokenSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'mobile'."
11-03-2021 14:07:11 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:07:11 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:07:12 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:07:13 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:07:13 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:07:39 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:07:39 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:07:58 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:07:58 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:07:58 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:08:06 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:08:06 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:08:13 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:08:13 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:08:13 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:09:54 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:09:54 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:09:54 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:11:17 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:11:17 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:11:18 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:11:27 ERROR    [log.py:224] Internal Server Error: /api/user/token/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 95, in get_attribute
    instance = instance[attr]
KeyError: 'mobile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 25, in post
    return Response(data={"data": serializer.data},
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 248, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
KeyError: "Got KeyError when attempting to get a value for field `mobile` on serializer `CreateTokenSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'mobile'."
11-03-2021 14:11:58 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:11:58 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:11:58 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:12:03 ERROR    [log.py:224] Internal Server Error: /api/user/token/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 95, in get_attribute
    instance = instance[attr]
KeyError: 'mobile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 25, in post
    return Response(data={"data": serializer.data},
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 248, in data
    self._data = self.to_representation(self.validated_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
KeyError: "Got KeyError when attempting to get a value for field `mobile` on serializer `CreateTokenSerializer`.\nThe serializer field might be named incorrectly and not match any attribute or key on the `dict` instance.\nOriginal exception text was: 'mobile'."
11-03-2021 14:12:47 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:12:47 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:12:47 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:12:50 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:12:50 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:13:13 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:13:13 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:13:13 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:14:09 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:14:09 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:14:09 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:14:33 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:14:33 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:14:33 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:14:46 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:14:46 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:17:24 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:17:24 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:17:25 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:17:42 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:17:42 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:17:53 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:17:53 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:18:15 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 14:18:15 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:18:15 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:18:35 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:18:35 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:18:54 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 14:18:54 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:18:54 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:19:26 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 14:19:26 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:19:26 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:19:39 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:19:39 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:19:55 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 14:19:55 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:19:55 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:20:04 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:20:04 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:20:25 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 14:20:25 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:20:26 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:24:24 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 14:24:24 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:24:24 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:24:54 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 14:24:54 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:24:54 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:25:08 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py changed, reloading.
11-03-2021 14:25:08 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:25:08 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:25:47 WARNING  [log.py:224] Unauthorized: /api/user/me/
11-03-2021 14:25:47 WARNING  [log.py:224] Unauthorized: /api/user/me/
11-03-2021 14:25:57 WARNING  [log.py:224] Unauthorized: /api/user/me/
11-03-2021 14:25:57 WARNING  [log.py:224] Unauthorized: /api/user/me/
11-03-2021 14:27:57 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 14:27:57 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:27:58 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:28:01 WARNING  [log.py:224] Unauthorized: /api/user/me/
11-03-2021 14:28:12 WARNING  [log.py:224] Unauthorized: /api/user/me/
11-03-2021 14:28:29 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 14:28:29 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:28:29 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:28:30 WARNING  [log.py:224] Unauthorized: /api/user/me/
11-03-2021 14:37:06 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
11-03-2021 14:37:06 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
11-03-2021 14:37:07 WARNING  [log.py:224] Method Not Allowed: /api/user/register/
11-03-2021 14:38:53 WARNING  [log.py:224] Bad Request: /api/user/register/
11-03-2021 14:39:05 WARNING  [log.py:224] Bad Request: /api/user/register/
11-03-2021 14:39:20 WARNING  [log.py:224] Bad Request: /api/user/register/
11-03-2021 14:40:25 WARNING  [log.py:224] Bad Request: /api/user/token/
11-03-2021 14:44:07 WARNING  [log.py:224] Unauthorized: /api/user/me/
11-03-2021 14:45:19 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 14:45:19 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:45:31 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:45:43 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 14:45:50 WARNING  [log.py:224] Method Not Allowed: /api/user/me/
11-03-2021 14:46:18 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 14:46:18 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 14:46:19 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:03:08 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 15:03:08 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:03:11 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:03:29 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 15:03:29 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:03:30 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:03:51 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 15:03:51 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:03:52 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:04:30 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 15:04:30 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:04:30 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:04:48 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py changed, reloading.
11-03-2021 15:04:48 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:04:48 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:04:51 WARNING  [log.py:224] Unauthorized: /api/user/me/
11-03-2021 15:05:35 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 41, in get
    request.user.auth_token.delete()
AttributeError: 'User' object has no attribute 'auth_token'
11-03-2021 15:05:57 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 15:05:57 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:05:57 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:10:59 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 15:10:59 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:11:00 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:11:30 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 15:11:30 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:11:30 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:12:47 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 15:12:47 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:12:47 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:13:52 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:13:52 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:13:53 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:14:44 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:14:44 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:14:44 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:15:17 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:15:17 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:15:17 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:15:29 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:15:29 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:15:30 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:16:10 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:16:10 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:16:10 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:16:26 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:16:26 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:16:26 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:16:47 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:16:47 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:16:47 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:17:00 WARNING  [log.py:224] Unauthorized: /api/user/logout/
11-03-2021 15:17:05 WARNING  [log.py:224] Bad Request: /api/user/register/
11-03-2021 15:17:24 WARNING  [log.py:224] Bad Request: /api/user/logout/
11-03-2021 15:19:51 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:19:51 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:19:51 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:20:23 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:20:23 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:20:24 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:21:25 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
11-03-2021 15:21:25 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:21:26 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:21:55 WARNING  [log.py:224] Bad Request: /api/user/logout/
11-03-2021 15:22:11 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:22:11 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:22:11 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:22:15 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 43, in post
    serializer.is_valid(raise_exception=True)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 60, in validate
    self.token = attrs['refresh']
KeyError: 'refresh'
11-03-2021 15:28:28 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:28:28 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:28:29 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:28:33 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:28:33 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:28:33 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:28:59 WARNING  [log.py:224] Bad Request: /api/user/logout/
11-03-2021 15:29:28 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 43, in post
    serializer.is_valid(raise_exception=True)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 60, in validate
    self.token = attrs['refresh']
KeyError: 'refresh'
11-03-2021 15:29:41 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:29:41 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:29:41 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:29:48 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 65, in save
    RefreshToken(self.token).blacklist()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 47, in __init__
    self.verify()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 100, in verify
    self.verify_token_type()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 112, in verify_token_type
    raise TokenError(_('Token has wrong type'))
rest_framework_simplejwt.exceptions.TokenError: Token has wrong type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 635, in fail
    msg = self.error_messages[key]
KeyError: 'Bad_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 44, in post
    serializer.save()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 67, in save
    self.fail('Bad_token')
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 639, in fail
    raise AssertionError(msg)
AssertionError: ValidationError raised by `LogoutSerializer`, but error key `Bad_token` does not exist in the `error_messages` dictionary.
11-03-2021 15:30:15 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:30:15 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:30:15 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:30:17 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 65, in save
    RefreshToken(self.token).blacklist()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 47, in __init__
    self.verify()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 100, in verify
    self.verify_token_type()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 112, in verify_token_type
    raise TokenError(_('Token has wrong type'))
rest_framework_simplejwt.exceptions.TokenError: Token has wrong type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 635, in fail
    msg = self.error_messages[key]
KeyError: 'Bad_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 44, in post
    serializer.save()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 67, in save
    self.fail('Bad_token')
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 639, in fail
    raise AssertionError(msg)
AssertionError: ValidationError raised by `LogoutSerializer`, but error key `Bad_token` does not exist in the `error_messages` dictionary.
11-03-2021 15:30:24 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:30:24 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:30:25 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:30:25 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 61, in save
    RefreshToken(self.token).blacklist()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 47, in __init__
    self.verify()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 100, in verify
    self.verify_token_type()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 112, in verify_token_type
    raise TokenError(_('Token has wrong type'))
rest_framework_simplejwt.exceptions.TokenError: Token has wrong type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 635, in fail
    msg = self.error_messages[key]
KeyError: 'Bad_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 44, in post
    serializer.save()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 63, in save
    self.fail('Bad_token')
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 639, in fail
    raise AssertionError(msg)
AssertionError: ValidationError raised by `LogoutSerializer`, but error key `Bad_token` does not exist in the `error_messages` dictionary.
11-03-2021 15:30:32 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:30:32 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:30:34 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:30:36 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 61, in save
    RefreshToken(self.token).blacklist()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 47, in __init__
    self.verify()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 100, in verify
    self.verify_token_type()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework_simplejwt/tokens.py", line 112, in verify_token_type
    raise TokenError(_('Token has wrong type'))
rest_framework_simplejwt.exceptions.TokenError: Token has wrong type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 635, in fail
    msg = self.error_messages[key]
KeyError: 'Bad_token'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 44, in post
    serializer.save()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 63, in save
    self.fail('Bad_token')
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 639, in fail
    raise AssertionError(msg)
AssertionError: ValidationError raised by `LogoutSerializer`, but error key `Bad_token` does not exist in the `error_messages` dictionary.
11-03-2021 15:30:44 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:30:44 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:30:45 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:34:56 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:34:56 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:34:56 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:34:58 WARNING  [log.py:224] Unauthorized: /api/user/logout/
11-03-2021 15:35:23 WARNING  [log.py:224] Unauthorized: /api/user/logout/
11-03-2021 15:35:25 WARNING  [log.py:224] Unauthorized: /api/user/logout/
11-03-2021 15:35:26 WARNING  [log.py:224] Unauthorized: /api/user/logout/
11-03-2021 15:36:04 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 44, in post
    serializer.save()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 65, in save
    RefreshToken(self.token).blacklist()
AttributeError: 'RefreshToken' object has no attribute 'blacklist'
11-03-2021 15:36:24 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:36:24 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:36:24 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:36:26 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 44, in post
    serializer.save()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 65, in save
    RefreshToken(self.token).blacklist(self)
AttributeError: 'RefreshToken' object has no attribute 'blacklist'
11-03-2021 15:37:13 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:37:13 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:37:13 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:38:55 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:38:55 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:39:55 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:41:23 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:41:23 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:41:23 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:41:54 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:41:54 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:41:54 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:42:34 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 44, in post
    serializer.save()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 66, in save
    token.blacklist()
AttributeError: 'RefreshToken' object has no attribute 'blacklist'
11-03-2021 15:43:44 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
11-03-2021 15:43:44 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:43:45 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:43:46 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:43:46 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:44:07 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:44:12 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:44:18 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:45:02 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 44, in post
    serializer.save()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 66, in save
    RefreshToken(self.token).blacklist()
AttributeError: 'RefreshToken' object has no attribute 'blacklist'
11-03-2021 15:46:01 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 15:46:01 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:46:01 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:46:03 ERROR    [log.py:224] Internal Server Error: /api/user/logout/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 54, in post
    sz.save()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 66, in save
    RefreshToken(self.token).blacklist()
AttributeError: 'RefreshToken' object has no attribute 'blacklist'
11-03-2021 15:46:31 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
11-03-2021 15:46:31 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:46:31 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:47:01 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
11-03-2021 15:47:01 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:47:01 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:47:05 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:47:05 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:47:11 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:47:16 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:47:20 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:47:40 WARNING  [log.py:224] Bad Request: /api/user/logout/
11-03-2021 15:48:43 WARNING  [log.py:224] Unauthorized: /api/user/me/
11-03-2021 15:53:13 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
11-03-2021 15:53:13 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:53:13 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:53:28 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
11-03-2021 15:53:28 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:53:28 INFO     [autoreload.py:617] Watching for file changes with StatReloader
11-03-2021 15:54:02 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
11-03-2021 15:54:02 DEBUG    [selector_events.py:59] Using selector: EpollSelector
11-03-2021 15:54:02 INFO     [autoreload.py:617] Watching for file changes with StatReloader
12-03-2021 10:09:40 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
12-03-2021 10:09:40 DEBUG    [selector_events.py:59] Using selector: EpollSelector
12-03-2021 12:09:47 INFO     [autoreload.py:617] Watching for file changes with StatReloader
12-03-2021 12:41:14 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
12-03-2021 12:41:14 DEBUG    [selector_events.py:59] Using selector: EpollSelector
12-03-2021 12:41:14 INFO     [autoreload.py:617] Watching for file changes with StatReloader
12-03-2021 12:41:39 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
12-03-2021 12:41:39 DEBUG    [selector_events.py:59] Using selector: EpollSelector
12-03-2021 12:41:39 INFO     [autoreload.py:617] Watching for file changes with StatReloader
12-03-2021 13:00:29 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
12-03-2021 13:00:29 DEBUG    [selector_events.py:59] Using selector: EpollSelector
12-03-2021 13:00:29 INFO     [autoreload.py:617] Watching for file changes with StatReloader
12-03-2021 13:00:59 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
12-03-2021 13:00:59 DEBUG    [selector_events.py:59] Using selector: EpollSelector
12-03-2021 13:01:00 INFO     [autoreload.py:617] Watching for file changes with StatReloader
12-03-2021 13:01:17 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
12-03-2021 13:01:17 DEBUG    [selector_events.py:59] Using selector: EpollSelector
12-03-2021 13:01:18 INFO     [autoreload.py:617] Watching for file changes with StatReloader
12-03-2021 13:05:09 WARNING  [log.py:224] Unauthorized: /api/user/me/
12-03-2021 13:05:18 DEBUG    [selector_events.py:59] Using selector: EpollSelector
12-03-2021 11:05:18 DEBUG    [selector_events.py:59] Using selector: EpollSelector
12-03-2021 13:05:20 INFO     [autoreload.py:617] Watching for file changes with StatReloader
12-03-2021 13:05:24 WARNING  [log.py:224] Unauthorized: /api/user/me/
12-03-2021 13:05:37 WARNING  [log.py:224] Unauthorized: /api/user/me/
12-03-2021 13:05:55 WARNING  [log.py:224] Unauthorized: /api/user/me/
13-03-2021 11:14:18 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/urls.py changed, reloading.
13-03-2021 11:14:18 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:14:24 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 11:18:04 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:18:04 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:18:06 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 11:18:18 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
13-03-2021 11:18:18 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:18:18 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 11:18:23 ERROR    [views.py:8] Page not found error 404 {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'register/' [name='register']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'token/' [name='token']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'me/' [name='me']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'logout/' [name='logout']>]], 'path': 'api/user/me/ss'}
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 576, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'register/' [name='register']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'token/' [name='token']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'me/' [name='me']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'logout/' [name='logout']>]], 'path': 'api/user/me/ss'}
13-03-2021 11:18:23 WARNING  [log.py:224] Not Found: /api/user/me/ss
13-03-2021 11:18:33 WARNING  [log.py:224] Unauthorized: /api/user/me/
13-03-2021 11:18:47 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/views.py changed, reloading.
13-03-2021 11:18:47 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:18:48 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 11:19:16 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/views.py changed, reloading.
13-03-2021 11:19:16 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:19:16 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 11:19:17 WARNING  [log.py:224] Unauthorized: /api/user/me/
13-03-2021 11:19:20 ERROR    [views.py:8] Page not found error 404 {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'register/' [name='register']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'token/' [name='token']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'me/' [name='me']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'logout/' [name='logout']>]], 'path': 'api/user/me/ss'}
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 576, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'register/' [name='register']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'token/' [name='token']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'me/' [name='me']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'logout/' [name='logout']>]], 'path': 'api/user/me/ss'}
13-03-2021 11:19:20 WARNING  [log.py:224] Not Found: /api/user/me/ss
13-03-2021 11:19:34 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/views.py changed, reloading.
13-03-2021 11:19:34 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:19:34 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 11:19:34 ERROR    [views.py:8] Page not found error 404 {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'register/' [name='register']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'token/' [name='token']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'me/' [name='me']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'logout/' [name='logout']>]], 'path': 'api/user/me/ss'}
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 576, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'register/' [name='register']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'token/' [name='token']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'me/' [name='me']>], [<URLResolver <module 'accounts.urls' from '/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py'> (accounts:accounts) 'api/user/'>, <URLPattern 'logout/' [name='logout']>]], 'path': 'api/user/me/ss'}
13-03-2021 11:19:34 WARNING  [log.py:224] Not Found: /api/user/me/ss
13-03-2021 11:26:24 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 11:26:24 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:26:24 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 11:26:31 WARNING  [log.py:224] Unauthorized: /api/user/me/
13-03-2021 11:26:50 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 11:26:50 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:26:51 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 11:27:05 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 11:27:05 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:27:06 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 11:30:17 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
13-03-2021 11:30:17 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:30:17 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 11:31:24 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 11:31:24 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:41:37 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:42:18 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:42:18 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:42:18 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:42:31 WARNING  [log.py:224] Bad Request: /api/user/register/
13-03-2021 12:42:45 WARNING  [log.py:224] Bad Request: /api/user/register/
13-03-2021 12:42:56 ERROR    [views.py:15] Internal Server Error 500
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 32, in post
    verified_url = RegisterView.construct_link_to_verify_user(request, user)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 20, in construct_link_to_verify_user
    relative_link = reverse('verify')
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'verify' not found. 'verify' is not a valid view function or pattern name.
13-03-2021 12:42:56 ERROR    [log.py:224] Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 32, in post
    verified_url = RegisterView.construct_link_to_verify_user(request, user)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 20, in construct_link_to_verify_user
    relative_link = reverse('verify')
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'verify' not found. 'verify' is not a valid view function or pattern name.
13-03-2021 12:43:12 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/project/settings.py changed, reloading.
13-03-2021 12:43:12 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:43:12 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:43:14 WARNING  [log.py:224] Bad Request: /api/user/register/
13-03-2021 12:43:23 ERROR    [log.py:224] Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 32, in post
    verified_url = RegisterView.construct_link_to_verify_user(request, user)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 20, in construct_link_to_verify_user
    relative_link = reverse('verify')
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'verify' not found. 'verify' is not a valid view function or pattern name.
13-03-2021 12:43:58 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py changed, reloading.
13-03-2021 12:43:58 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:43:58 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:44:53 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:44:53 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:44:53 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:45:04 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:45:04 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:45:04 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:45:12 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:45:12 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:45:12 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:45:18 ERROR    [log.py:224] Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 32, in post
    verified_url = RegisterView.construct_link_to_verify_user(request, user)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 20, in construct_link_to_verify_user
    relative_link = reverse('verify')
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'verify' not found. 'verify' is not a valid view function or pattern name.
13-03-2021 12:46:05 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:46:05 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:46:05 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:46:10 WARNING  [log.py:224] Bad Request: /api/user/register/
13-03-2021 12:46:15 ERROR    [log.py:224] Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 33, in post
    body = f""" Hi {user.email} Use This Link to Verify your email
AttributeError: 'User' object has no attribute 'email'
13-03-2021 12:46:31 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:46:31 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:46:31 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:47:26 WARNING  [log.py:224] Bad Request: /api/user/register/
13-03-2021 12:49:29 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:49:29 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:49:33 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:50:02 ERROR    [log.py:224] Internal Server Error: /api/user/verify/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
13-03-2021 12:51:00 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:51:00 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:51:00 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:51:33 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:51:33 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:51:34 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:52:02 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:52:02 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:52:02 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:52:32 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:52:32 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:52:32 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:53:21 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:53:21 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:53:22 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:54:03 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:54:03 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:54:04 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:55:22 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:55:22 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:55:22 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:56:03 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:56:03 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:56:03 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:56:35 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:56:35 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:56:35 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:57:09 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:57:09 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:57:10 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:57:45 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:57:45 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:57:45 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:58:47 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:58:47 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:58:47 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:59:49 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 12:59:49 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 12:59:49 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 12:59:52 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
13-03-2021 12:59:52 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
13-03-2021 12:59:53 WARNING  [log.py:224] Bad Request: /api/user/verify/
13-03-2021 13:32:21 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 13:32:21 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:32:22 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:33:01 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:33:01 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:33:16 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:33:30 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:34:11 WARNING  [log.py:224] Unauthorized: /api/user/token/
13-03-2021 13:34:47 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
13-03-2021 13:34:47 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
13-03-2021 13:34:47 WARNING  [log.py:224] Bad Request: /api/user/verify/
13-03-2021 13:35:22 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 13:35:22 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:35:22 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:35:26 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
13-03-2021 13:35:26 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
13-03-2021 13:35:26 WARNING  [log.py:224] Bad Request: /api/user/verify/
13-03-2021 13:36:06 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 13:36:06 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:36:06 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:36:10 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
13-03-2021 13:36:10 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
13-03-2021 13:36:10 WARNING  [log.py:224] Bad Request: /api/user/verify/
13-03-2021 13:36:35 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 13:36:35 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:36:35 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:36:37 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
13-03-2021 13:36:37 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
13-03-2021 13:36:37 WARNING  [log.py:224] Bad Request: /api/user/verify/
13-03-2021 13:36:55 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 13:36:55 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:36:55 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:36:57 ERROR    [log.py:224] Internal Server Error: /api/user/verify/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 48, in get
    payload = jwt.decode(token, settings.SECRET_KEY)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/jwt/api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/jwt/api_jwt.py", line 79, in decode_complete
    raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
13-03-2021 13:39:02 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 13:39:02 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:39:03 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:39:07 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
13-03-2021 13:39:07 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
13-03-2021 13:39:07 WARNING  [log.py:224] Bad Request: /api/user/verify/
13-03-2021 13:39:20 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 13:39:20 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:39:21 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:39:23 ERROR    [log.py:224] Internal Server Error: /api/user/verify/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 48, in get
    payload = jwt.decode(token, settings.SECRET_KEY, verify=False)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/jwt/api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/jwt/api_jwt.py", line 79, in decode_complete
    raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
13-03-2021 13:39:32 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 13:39:32 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:39:33 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:40:00 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 13:40:00 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:40:00 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:40:01 ERROR    [log.py:224] Internal Server Error: /api/user/verify/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 48, in get
    payload = jwt.decode(token, settings.SECRET_KEY,algorithm=["HS256"])
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/jwt/api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/jwt/api_jwt.py", line 79, in decode_complete
    raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
13-03-2021 13:40:08 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:40:08 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:40:09 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:40:14 ERROR    [log.py:224] Internal Server Error: /api/user/verify/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 48, in get
    payload = jwt.decode(token, settings.SECRET_KEY,algorithm=["HS256"])
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/jwt/api_jwt.py", line 113, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/jwt/api_jwt.py", line 79, in decode_complete
    raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
13-03-2021 13:40:44 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:40:44 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:41:16 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 13:41:20 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
13-03-2021 13:41:20 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
13-03-2021 13:41:30 DEBUG    [core.py:163] Successfully imported extension module "markdown.extensions.toc".
13-03-2021 13:41:30 DEBUG    [core.py:126] Successfully loaded extension "markdown.extensions.toc.TocExtension".
13-03-2021 13:41:43 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 13:41:43 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 13:41:43 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 14:13:40 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 14:13:47 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/email.py changed, reloading.
13-03-2021 14:13:47 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 14:13:48 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 14:13:49 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 14:13:49 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 14:59:40 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 14:59:45 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:10:32 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:10:43 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:10:43 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:10:54 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:10:59 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:11:09 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:11:20 ERROR    [log.py:224] Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 35, in post
    otp = otp_generator()[:4]
TypeError: 'int' object is not subscriptable
13-03-2021 15:11:59 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 15:11:59 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:11:59 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:12:33 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/send_sms.py changed, reloading.
13-03-2021 15:12:33 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:12:34 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:12:39 WARNING  [log.py:224] Bad Request: /api/user/register/
13-03-2021 15:12:43 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:12:43 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:12:51 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:13:00 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:13:45 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 15:13:45 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:13:45 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:13:54 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:13:54 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:13:58 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:14:00 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:14:00 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:14:02 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:14:10 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:14:14 INFO     [http_client.py:79] POST Request: https://api.twilio.com/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json
13-03-2021 15:14:14 INFO     [http_client.py:81] PAYLOAD: {'To': '01066243716', 'From': '+15034655860', 'Body': 2887}
13-03-2021 15:14:14 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): api.twilio.com:443
13-03-2021 15:14:15 DEBUG    [connectionpool.py:452] https://api.twilio.com:443 "POST /2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json HTTP/1.1" 400 158
13-03-2021 15:14:15 INFO     [http_client.py:97] POST Response: 400 {"code": 21211, "message": "The 'To' number 01066243716 is not a valid phone number.", "more_info": "https://www.twilio.com/docs/errors/21211", "status": 400}
13-03-2021 15:15:47 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/send_sms.py changed, reloading.
13-03-2021 15:15:47 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:15:48 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:15:49 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:15:49 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:16:00 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:16:08 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:16:12 ERROR    [log.py:224] Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 37, in post
    res = sms.send()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/send_sms.py", line 21, in send
    to=2 + self.to  # 201066243716
TypeError: unsupported operand type(s) for +: 'int' and 'str'
13-03-2021 15:16:31 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/send_sms.py changed, reloading.
13-03-2021 15:16:31 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:16:32 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:17:06 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/send_sms.py changed, reloading.
13-03-2021 15:17:06 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:17:06 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:17:51 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/send_sms.py changed, reloading.
13-03-2021 15:17:51 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:17:51 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:17:54 WARNING  [log.py:224] Bad Request: /api/user/register/
13-03-2021 15:17:57 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:17:57 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:18:03 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:18:06 ERROR    [log.py:224] Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: accounts_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 31, in post
    serializer.is_valid(raise_exception=True)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 419, in run_validation
    value = self.to_internal_value(data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 476, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 799, in run_validation
    return super().run_validation(data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 569, in run_validation
    self.run_validators(value)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 591, in run_validators
    validator(value, self)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/validators.py", line 73, in __call__
    if qs_exists(queryset):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/validators.py", line 21, in qs_exists
    return queryset.exists()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/query.py", line 809, in exists
    return self.query.has_results(using=self.db)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 535, in has_results
    return compiler.has_results()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1126, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: accounts_user
13-03-2021 15:18:12 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:18:12 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:18:14 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:18:23 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:18:26 INFO     [http_client.py:79] POST Request: https://api.twilio.com/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json
13-03-2021 15:18:26 INFO     [http_client.py:81] PAYLOAD: {'To': '201066243716', 'From': '+15034655860', 'Body': 4979}
13-03-2021 15:18:26 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): api.twilio.com:443
13-03-2021 15:18:27 DEBUG    [connectionpool.py:452] https://api.twilio.com:443 "POST /2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json HTTP/1.1" 400 159
13-03-2021 15:18:27 INFO     [http_client.py:97] POST Response: 400 {"code": 21211, "message": "The 'To' number 201066243716 is not a valid phone number.", "more_info": "https://www.twilio.com/docs/errors/21211", "status": 400}
13-03-2021 15:18:59 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/send_sms.py changed, reloading.
13-03-2021 15:18:59 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:18:59 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:19:01 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:19:01 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:19:07 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:19:07 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:19:08 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:19:09 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:19:18 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:19:21 INFO     [http_client.py:79] POST Request: https://api.twilio.com/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json
13-03-2021 15:19:21 INFO     [http_client.py:81] PAYLOAD: {'To': '+201066243716', 'From': '+15034655860', 'Body': 6074}
13-03-2021 15:19:21 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): api.twilio.com:443
13-03-2021 15:19:22 DEBUG    [connectionpool.py:452] https://api.twilio.com:443 "POST /2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json HTTP/1.1" 201 807
13-03-2021 15:19:22 INFO     [http_client.py:97] POST Response: 201 {"sid": "SM19d26b80e89c449bbe6e5bcb1eb4b8f0", "date_created": "Sat, 13 Mar 2021 13:19:22 +0000", "date_updated": "Sat, 13 Mar 2021 13:19:22 +0000", "date_sent": null, "account_sid": "AC5860a17c2df9813ef653c3ff4e808d1a", "to": "+201066243716", "from": "+15034655860", "messaging_service_sid": null, "body": "Sent from your Twilio trial account - 6074", "status": "queued", "num_segments": "1", "num_media": "0", "direction": "outbound-api", "api_version": "2010-04-01", "price": null, "price_unit": "USD", "error_code": null, "error_message": null, "uri": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM19d26b80e89c449bbe6e5bcb1eb4b8f0.json", "subresource_uris": {"media": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM19d26b80e89c449bbe6e5bcb1eb4b8f0/Media.json"}}
13-03-2021 15:19:41 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 15:19:41 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:19:41 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:20:06 INFO     [http_client.py:79] POST Request: https://api.twilio.com/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json
13-03-2021 15:20:06 INFO     [http_client.py:81] PAYLOAD: {'To': '+201004770721', 'From': '+15034655860', 'Body': 9466}
13-03-2021 15:20:06 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): api.twilio.com:443
13-03-2021 15:20:07 DEBUG    [connectionpool.py:452] https://api.twilio.com:443 "POST /2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json HTTP/1.1" 400 314
13-03-2021 15:20:07 INFO     [http_client.py:97] POST Response: 400 {"code": 21608, "message": "The number  is unverified. Trial accounts cannot send messages to unverified numbers; verify  at twilio.com/user/account/phone-numbers/verified, or purchase a Twilio number to send messages to unverified numbers.", "more_info": "https://www.twilio.com/docs/errors/21608", "status": 400}
13-03-2021 15:20:07 ERROR    [log.py:224] Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 38, in post
    print(res.status)
AttributeError: 'NoneType' object has no attribute 'status'
13-03-2021 15:20:17 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 15:20:17 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:20:17 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:20:18 WARNING  [log.py:224] Bad Request: /api/user/register/
13-03-2021 15:20:22 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:20:22 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:20:28 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:20:40 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:20:45 INFO     [http_client.py:79] POST Request: https://api.twilio.com/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json
13-03-2021 15:20:45 INFO     [http_client.py:81] PAYLOAD: {'To': '+201004770721', 'From': '+15034655860', 'Body': 9936}
13-03-2021 15:20:45 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): api.twilio.com:443
13-03-2021 15:20:46 DEBUG    [connectionpool.py:452] https://api.twilio.com:443 "POST /2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json HTTP/1.1" 400 314
13-03-2021 15:20:46 INFO     [http_client.py:97] POST Response: 400 {"code": 21608, "message": "The number  is unverified. Trial accounts cannot send messages to unverified numbers; verify  at twilio.com/user/account/phone-numbers/verified, or purchase a Twilio number to send messages to unverified numbers.", "more_info": "https://www.twilio.com/docs/errors/21608", "status": 400}
13-03-2021 15:20:46 ERROR    [log.py:224] Internal Server Error: /api/user/register/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 38, in post
    print(res.status_code)
AttributeError: 'NoneType' object has no attribute 'status_code'
13-03-2021 15:20:59 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 15:20:59 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:21:00 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:21:03 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:21:03 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:21:09 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:21:16 INFO     [autoreload.py:617] Watching for file changes with StatReloader
13-03-2021 15:21:20 INFO     [http_client.py:79] POST Request: https://api.twilio.com/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json
13-03-2021 15:21:20 INFO     [http_client.py:81] PAYLOAD: {'To': '+201004770721', 'From': '+15034655860', 'Body': 8678}
13-03-2021 15:21:20 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): api.twilio.com:443
13-03-2021 15:21:21 DEBUG    [connectionpool.py:452] https://api.twilio.com:443 "POST /2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json HTTP/1.1" 400 314
13-03-2021 15:21:21 INFO     [http_client.py:97] POST Response: 400 {"code": 21608, "message": "The number  is unverified. Trial accounts cannot send messages to unverified numbers; verify  at twilio.com/user/account/phone-numbers/verified, or purchase a Twilio number to send messages to unverified numbers.", "more_info": "https://www.twilio.com/docs/errors/21608", "status": 400}
13-03-2021 15:24:23 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
13-03-2021 15:24:23 DEBUG    [selector_events.py:59] Using selector: EpollSelector
13-03-2021 15:24:24 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:02:33 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:08:37 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
15-03-2021 20:08:37 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:08:38 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:08:38 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:08:38 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:08:46 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:09:01 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:09:14 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:09:22 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:09:36 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:10:32 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
15-03-2021 20:10:32 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:10:33 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:13:10 INFO     [http_client.py:79] POST Request: https://api.twilio.com/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json
15-03-2021 20:13:10 INFO     [http_client.py:81] PAYLOAD: {'To': '+201066243716', 'From': '+15034655860', 'Body': 7727}
15-03-2021 20:13:10 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): api.twilio.com:443
15-03-2021 20:13:11 DEBUG    [connectionpool.py:452] https://api.twilio.com:443 "POST /2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json HTTP/1.1" 201 807
15-03-2021 20:13:11 INFO     [http_client.py:97] POST Response: 201 {"sid": "SM1b2d48bc62e64a7fb7570747246740ab", "date_created": "Mon, 15 Mar 2021 18:13:11 +0000", "date_updated": "Mon, 15 Mar 2021 18:13:11 +0000", "date_sent": null, "account_sid": "AC5860a17c2df9813ef653c3ff4e808d1a", "to": "+201066243716", "from": "+15034655860", "messaging_service_sid": null, "body": "Sent from your Twilio trial account - 7727", "status": "queued", "num_segments": "1", "num_media": "0", "direction": "outbound-api", "api_version": "2010-04-01", "price": null, "price_unit": "USD", "error_code": null, "error_message": null, "uri": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM1b2d48bc62e64a7fb7570747246740ab.json", "subresource_uris": {"media": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM1b2d48bc62e64a7fb7570747246740ab/Media.json"}}
15-03-2021 20:13:18 WARNING  [log.py:224] Unauthorized: /api/user/token/
15-03-2021 20:13:29 WARNING  [log.py:224] Unauthorized: /api/user/token/
15-03-2021 20:14:22 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:14:22 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:14:32 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:14:34 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:14:53 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:15:01 INFO     [http_client.py:79] POST Request: https://api.twilio.com/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json
15-03-2021 20:15:01 INFO     [http_client.py:81] PAYLOAD: {'To': '+201066243716', 'From': '+15034655860', 'Body': 5867}
15-03-2021 20:15:01 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): api.twilio.com:443
15-03-2021 20:15:03 DEBUG    [connectionpool.py:452] https://api.twilio.com:443 "POST /2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json HTTP/1.1" 201 807
15-03-2021 20:15:03 INFO     [http_client.py:97] POST Response: 201 {"sid": "SM8ddf467c3e164298b6bdec4c9f24c818", "date_created": "Mon, 15 Mar 2021 18:15:03 +0000", "date_updated": "Mon, 15 Mar 2021 18:15:03 +0000", "date_sent": null, "account_sid": "AC5860a17c2df9813ef653c3ff4e808d1a", "to": "+201066243716", "from": "+15034655860", "messaging_service_sid": null, "body": "Sent from your Twilio trial account - 5867", "status": "queued", "num_segments": "1", "num_media": "0", "direction": "outbound-api", "api_version": "2010-04-01", "price": null, "price_unit": "USD", "error_code": null, "error_message": null, "uri": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM8ddf467c3e164298b6bdec4c9f24c818.json", "subresource_uris": {"media": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM8ddf467c3e164298b6bdec4c9f24c818/Media.json"}}
15-03-2021 20:15:58 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/admin.py changed, reloading.
15-03-2021 20:15:58 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:15:59 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:16:02 WARNING  [log.py:224] Not Found: /favicon.ico
15-03-2021 20:16:06 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:16:06 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:16:14 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:16:31 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:32:09 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
15-03-2021 20:32:09 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:32:09 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:32:29 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:32:29 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:32:30 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:33:19 WARNING  [log.py:224] Bad Request: /api/user/verify/
15-03-2021 20:34:20 WARNING  [log.py:224] Bad Request: /api/user/verify/
15-03-2021 20:34:46 ERROR    [log.py:224] Internal Server Error: /api/user/verify/
Traceback (most recent call last):
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py", line 55, in post
    serializer.is_valid(raise_exception=True)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py", line 37, in validate
    otp = PhoneOtp.objects.filter(user__mobile=mobile, token=token).first()
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1258, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1084, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'token' into field. Choices are: created_at, id, otp, updated_at, user, user_id
15-03-2021 20:36:00 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
15-03-2021 20:36:00 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:36:00 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:57:28 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:57:28 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:57:32 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:57:35 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:57:47 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:57:55 WARNING  [log.py:224] Unauthorized: /api/user/verify/
15-03-2021 20:58:03 INFO     [http_client.py:79] POST Request: https://api.twilio.com/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json
15-03-2021 20:58:03 INFO     [http_client.py:81] PAYLOAD: {'To': '+201066243716', 'From': '+15034655860', 'Body': 3113}
15-03-2021 20:58:03 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): api.twilio.com:443
15-03-2021 20:58:04 DEBUG    [connectionpool.py:452] https://api.twilio.com:443 "POST /2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json HTTP/1.1" 201 807
15-03-2021 20:58:04 INFO     [http_client.py:97] POST Response: 201 {"sid": "SM732f463c622545908e34bc8497808991", "date_created": "Mon, 15 Mar 2021 18:58:05 +0000", "date_updated": "Mon, 15 Mar 2021 18:58:05 +0000", "date_sent": null, "account_sid": "AC5860a17c2df9813ef653c3ff4e808d1a", "to": "+201066243716", "from": "+15034655860", "messaging_service_sid": null, "body": "Sent from your Twilio trial account - 3113", "status": "queued", "num_segments": "1", "num_media": "0", "direction": "outbound-api", "api_version": "2010-04-01", "price": null, "price_unit": "USD", "error_code": null, "error_message": null, "uri": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM732f463c622545908e34bc8497808991.json", "subresource_uris": {"media": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM732f463c622545908e34bc8497808991/Media.json"}}
15-03-2021 20:58:26 WARNING  [log.py:224] Unauthorized: /api/user/verify/
15-03-2021 20:59:47 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/serializers.py changed, reloading.
15-03-2021 20:59:47 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 20:59:47 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 20:59:52 WARNING  [log.py:224] Bad Request: /api/user/verify/
15-03-2021 21:00:08 WARNING  [log.py:224] Unauthorized: /api/user/verify/
15-03-2021 21:04:58 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/views.py changed, reloading.
15-03-2021 21:04:58 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:04:58 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 21:05:38 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/urls.py changed, reloading.
15-03-2021 21:05:38 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:05:39 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 21:06:39 INFO     [http_client.py:79] POST Request: https://api.twilio.com/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json
15-03-2021 21:06:39 INFO     [http_client.py:81] PAYLOAD: {'To': '+201066243716', 'From': '+15034655860', 'Body': 7853}
15-03-2021 21:06:39 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): api.twilio.com:443
15-03-2021 21:06:41 DEBUG    [connectionpool.py:452] https://api.twilio.com:443 "POST /2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json HTTP/1.1" 201 807
15-03-2021 21:06:41 INFO     [http_client.py:97] POST Response: 201 {"sid": "SM50d1050d842940b69933a2b79c1b59ef", "date_created": "Mon, 15 Mar 2021 19:06:42 +0000", "date_updated": "Mon, 15 Mar 2021 19:06:42 +0000", "date_sent": null, "account_sid": "AC5860a17c2df9813ef653c3ff4e808d1a", "to": "+201066243716", "from": "+15034655860", "messaging_service_sid": null, "body": "Sent from your Twilio trial account - 7853", "status": "queued", "num_segments": "1", "num_media": "0", "direction": "outbound-api", "api_version": "2010-04-01", "price": null, "price_unit": "USD", "error_code": null, "error_message": null, "uri": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM50d1050d842940b69933a2b79c1b59ef.json", "subresource_uris": {"media": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM50d1050d842940b69933a2b79c1b59ef/Media.json"}}
15-03-2021 21:06:54 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:06:55 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:07:07 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:07:20 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 21:08:05 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/accounts/models.py changed, reloading.
15-03-2021 21:08:05 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:08:05 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 21:08:11 INFO     [http_client.py:79] POST Request: https://api.twilio.com/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json
15-03-2021 21:08:11 INFO     [http_client.py:81] PAYLOAD: {'To': '+201066243716', 'From': '+15034655860', 'Body': 3876}
15-03-2021 21:08:11 DEBUG    [connectionpool.py:971] Starting new HTTPS connection (1): api.twilio.com:443
15-03-2021 21:08:13 DEBUG    [connectionpool.py:452] https://api.twilio.com:443 "POST /2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages.json HTTP/1.1" 201 807
15-03-2021 21:08:13 INFO     [http_client.py:97] POST Response: 201 {"sid": "SM6bcdfb43f7384c9c85765aec4b416950", "date_created": "Mon, 15 Mar 2021 19:08:13 +0000", "date_updated": "Mon, 15 Mar 2021 19:08:13 +0000", "date_sent": null, "account_sid": "AC5860a17c2df9813ef653c3ff4e808d1a", "to": "+201066243716", "from": "+15034655860", "messaging_service_sid": null, "body": "Sent from your Twilio trial account - 3876", "status": "queued", "num_segments": "1", "num_media": "0", "direction": "outbound-api", "api_version": "2010-04-01", "price": null, "price_unit": "USD", "error_code": null, "error_message": null, "uri": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM6bcdfb43f7384c9c85765aec4b416950.json", "subresource_uris": {"media": "/2010-04-01/Accounts/AC5860a17c2df9813ef653c3ff4e808d1a/Messages/SM6bcdfb43f7384c9c85765aec4b416950/Media.json"}}
15-03-2021 21:09:33 INFO     [autoreload.py:240] /home/mohamedwahba/Desktop/DEV/Custom-Api-Login-register/utils/send_sms.py changed, reloading.
15-03-2021 21:09:33 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:09:34 INFO     [autoreload.py:617] Watching for file changes with StatReloader
15-03-2021 21:13:29 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:13:30 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:20:46 WARNING  [log.py:224] Not Found: /
15-03-2021 21:20:50 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:41:22 WARNING  [log.py:224] Not Found: /
15-03-2021 21:41:22 WARNING  [log.py:224] Not Found: /favicon.ico
15-03-2021 21:41:29 WARNING  [log.py:224] Not Found: /static/admin/css/base.css
15-03-2021 21:41:29 WARNING  [log.py:224] Not Found: /static/admin/css/nav_sidebar.css
15-03-2021 21:41:29 WARNING  [log.py:224] Not Found: /static/admin/css/login.css
15-03-2021 21:41:29 WARNING  [log.py:224] Not Found: /static/admin/css/responsive.css
15-03-2021 21:41:29 WARNING  [log.py:224] Not Found: /static/admin/js/nav_sidebar.js
15-03-2021 21:50:54 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:51:05 DEBUG    [selector_events.py:59] Using selector: EpollSelector
15-03-2021 21:53:05 DEBUG    [selector_events.py:59] Using selector: EpollSelector
